export default [
  'the way an onion makes you cry',
  'the smell of a new book',
  'the smell of an old book',
  'the frustration of learning something for the first time',
  'the feeling when you finally understand a concept',
  'tasting perfectly in season fruit',
  'the hunger after a long workout',
  'laying in a bed with freshly cleaned sheets',
  'taking a shower after camping',
  'when your crush messages you',
  'your favorite song coming on the radio',
  'the smell of a fresh rain',
  'opening your window and feeling a breeze on a hot day',
  'crying so much that there are no more tears',
  'comfort food on a cold day',
];
